---
- name: DNS Setup Block
  block:
    - name: Install DNS packages
      ansible.builtin.dnf:
        name: "{{ dns_pkg }}"
        state: present

    - name: Configure DNS named.conf (only if not already set)
      template:
        src: named.conf.j2
        dest: "{{ dns_conf }}"
      notify: Restart DNS Service

    - name: Create forward zone if it doesn't exist
      template:
        src: forward.zone.j2
        dest: "{{ dns_path }}/forward.zone"
      when: not lookup('ansible.builtin.file', dns_path + '/forward.zone', errors='ignore')

    - name: Create reverse zone if it doesn't exist
      template:
        src: reverse.zone.j2
        dest: "{{ dns_path }}/reverse.zone"
      when: not lookup('ansible.builtin.file', dns_path + '/reverse.zone', errors='ignore')

    - name: Change Ownerships for zone files
      file:
        path: "{{ item }}"
        owner: root
        group: named
      loop: "{{ zone_files }}"
      when: item is exists

    - name: Start and Enable DNS Service
      service:
        name: "{{ dns_svc }}"
        state: started
        enabled: true

  rescue:
    - name: Rollback - Remove zone files if block fails
      file:
        path: "{{ item }}"
        state: absent
      loop: "{{ zone_files }}"

    - name: Rollback - Remove DNS config
      file:
        path: "{{ dns_conf }}"
        state: absent

    - name: Rollback - Stop DNS service
      service:
        name: "{{ dns_svc }}"
        state: stopped
        enabled: false

  always:
    - name: Ensure SELinux context is correct (optional)
      command: restorecon -Rv /var/named
      changed_when: false


