---
- name: Install firewalld
  package:
    name: firewalld
    state: present

- name: Ensure firewalld is started and enabled
  service:
    name: firewalld
    state: "{{ firewall_state }}"
    enabled: "{{ firewall_enabled }}"

- name: Manage firewall services
  firewalld:
    service: "{{ item.name }}"
    permanent: true
    state: "{{ item.state }}"
    immediate: true
  loop: "{{ firewall_services }}"
  notify: Reload firewalld

- name: Manage firewall ports
  firewalld:
    port: "{{ item.port }}"
    permanent: true
    state: "{{ item.state }}"
    immediate: true
  loop: "{{ firewall_ports }}"
  notify: Reload firewalld

