---
- name: Install NFS Server 
  dnf: 
    name: "{{ nfs_pkg }}" 
    state: present 
- name: Creating Mount Point Directory 
  file: 
    dest: "{{ nfsdir }}"
    owner: "{{ nfsown }}"
    group: "{{ nfsown }}"
    mode: '0775'
    state: directory 
- name: export entry in nfs path
  copy: 
    content: "/nfs-server *(rw,sync,no_root_squash)\n"
    dest: "{{ exp_dir }}" 
  notify: nfs

- name: start and enable nfs service
  service: 
    name: '{{ nfs_svc }}'
    enabled: true
    state: started

- name: run command showmount. 
  shell: showmount -e 
  register: output

- name: getting output showmount 
  debug: 
    var: output.stdout_lines

- name: Mount an NFS volume
  ansible.posix.mount:
    src: '{{ ansible_default_ipv4.address }}:/{{ nfsdir }}'
    path: "{{ mpath }}"
    opts: rw,sync,hard
    state: present
    fstype: nfs

- name: Capture task output
  shell: cat /etc/fstab | grep /mnt 
  register: nfs_out
- name: Showing /mnt mount point
  debug:
    var: nfs_out.stdout_lines

- name: Update Mount Point runtime
  ansible.posix.mount:
    src: '{{ ansible_default_ipv4.address }}:/{{ nfsdir }}'
    path: "{{ mpath }}"
    opts: rw,sync,hard
    state: mounted
    fstype: nfs
